name: Build Mkdocs Site
description: Builds the St Clair Community Mkdocs site.
inputs:
  config:
    description: The path to the mkdocs.yml file.
    required: false
    default: .github/mkdocs.yml
runs:
  using: docker
  image: ghcr.io/${{ github.action_repository }}:${{ github.action_ref }}
  env:
    GIT_USERNAME: ${{ github.actor }}
    GIT_USER_ID: ${{ github.actor_id }}
    MKDOCS_CONFIG: ${{ inputs.config }}
