name: Build & Publish Docker Image
on:
  push:
    branches: [ main ]
    paths:
      - Dockerfile
      - .github/workflows/docker-build-push.yml
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set image name
        id: image
        run: |
          IMAGE="ghcr.io/${{ github.repository_owner }}/myapp:latest"
          echo "image=$IMAGE" >> $GITHUB_OUTPUT
      - name: Build and tag Docker image
        run: |
          docker build -t ${{ steps.image.outputs.image }} .
      - name: Push Docker image
        run: |
          docker push ${{ steps.image.outputs.image }}